name: Apply Patch and (optional) Build

on:
  workflow_dispatch:
    inputs:
      PATCH_B64:
        description: "Base64-kodiertes TAR-Archiv mit Dateien, die ins Repo kopiert/überschrieben werden"
        required: true
      BUILD:
        description: "EAS Build auslösen?"
        required: false
        default: "true"
      EAS_PROFILE:
        description: "EAS Build Profile (z.B. preview)"
        required: false
        default: "preview"
      EAS_PROJECT_ID:
        description: "Optional: EAS Project ID (falls nicht in app.json extra.eas.projectId hinterlegt)"
        required: false
        default: ""

jobs:
  apply-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Decode and extract patch
        run: |
          echo "${{ inputs.PATCH_B64 }}" | base64 -d > patch.tgz
          tar -xzf patch.tgz
          rm -f patch.tgz
          echo "Patched files:"
          git status --porcelain

      - name: Commit changes
        env:
          ACTOR: ${{ github.actor }}
        run: |
          git config user.name "${ACTOR}"
          git config user.email "${ACTOR}@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: apply automated patch"
            git push
          fi

      - name: Resolve EAS Project ID
        id: proj
        run: |
          APP_JSON="app.json"
          if [ -f "$APP_JSON" ]; then
            PID=$(jq -r '.expo.extra.eas.projectId // empty' "$APP_JSON" || true)
          fi
          if [ -z "$PID" ]; then
            PID="${{ inputs.EAS_PROJECT_ID }}"
          fi
          if [ -z "$PID" ]; then
            echo "EAS Project ID fehlt. Entweder in app.json (.expo.extra.eas.projectId) setzen oder als Input EAS_PROJECT_ID übergeben." >&2
            echo "pid=" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "pid=$PID" >> $GITHUB_OUTPUT

      - name: Trigger EAS Android Build (optional)
        if: ${{ inputs.BUILD == 'true' && steps.proj.outputs.pid != '' }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_PROJECT_ID: ${{ steps.proj.outputs.pid }}
          EAS_PROFILE: ${{ inputs.EAS_PROFILE }}
        run: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "Missing EXPO_TOKEN secret" >&2
            exit 1
          fi
          cat > graphql.json <<'EOF'
          {
            "query": "mutation CreateBuild($input: CreateBuildInput!) { createBuild(input: $input) { build { id status platform } } }",
            "variables": {
              "input": {
                "appId": "__APP_ID__",
                "platform": "ANDROID",
                "profile": "__PROFILE__"
              }
            }
          }
          EOF
          sed -i "s/__APP_ID__/${EAS_PROJECT_ID}/" graphql.json
          sed -i "s/__PROFILE__/${EAS_PROFILE}/" graphql.json
          curl -f -sS -H "Content-Type: application/json" -H "Authorization: Bearer ${EXPO_TOKEN}" \
            -X POST --data @graphql.json https://api.expo.dev/v2/graphql | tee build_trigger_response.json
          BUILD_ID=$(cat build_trigger_response.json | python3 -c "import sys, json; d=json.load(sys.stdin); print(d['data']['createBuild']['build']['id'])")
          echo "Build ID: $BUILD_ID"
          echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT

      - name: Poll build status
        if: ${{ inputs.BUILD == 'true' && steps.proj.outputs.pid != '' }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          BUILD_ID=$(cat build_trigger_response.json | python3 -c "import sys, json; d=json.load(sys.stdin); print(d['data']['createBuild']['build']['id'])")
          echo "Polling ${BUILD_ID} ..."
          for i in $(seq 1 60); do
            curl -f -sS -H "Content-Type: application/json" -H "Authorization: Bearer ${EXPO_TOKEN}" \
              -X POST --data "{\"query\":\"query BuildById($id: ID!) { build(id: $id) { id status artifacts { buildUrl } } }\",\"variables\":{\"id\":\"${BUILD_ID}\"}}" \
              https://api.expo.dev/v2/graphql | tee build_status.json
            STATUS=$(cat build_status.json | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['data']['build']['status'])")
            echo "Status: ${STATUS}"
            if [ "${STATUS}" = "FINISHED" ]; then
              URL=$(cat build_status.json | python3 -c "import sys,json; d=json.load(sys.stdin); print((d['data']['build']['artifacts'] or {}).get('buildUrl',''))")
              echo "APK URL: ${URL}" >> $GITHUB_STEP_SUMMARY
              exit 0
            elif [ "${STATUS}" = "ERRORED" ]; then
              echo "Build failed"; cat build_status.json; exit 1
            fi
            sleep 10
          done
          echo "Timeout waiting for build"; exit 1
