name: Apply Patch and (optional) Build

on:
  workflow_dispatch:
    inputs:
      FILES_JSON:
        description: 'JSON: [{"path":"file","content":"…"}] – Dateien werden geschrieben/überschrieben'
        required: true
      BUILD:
        description: 'EAS Build auslösen?'
        required: false
        default: 'true'
      EAS_PROFILE:
        description: 'EAS Build Profile (z.B. preview)'
        required: false
        default: 'preview'
      EAS_PROJECT_ID:
        description: 'Optional: EAS Project ID (falls nicht in app.json extra.eas.projectId)'
        required: false
        default: ''

jobs:
  apply-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write files from JSON
        run: |
          echo '${{ inputs.FILES_JSON }}' > files.json
          python3 - <<'PY'
import os, json, base64
data = json.load(open("files.json"))
for f in data:
    p = f["path"]
    c = f["content"]
    os.makedirs(os.path.dirname(p) or ".", exist_ok=True)
    if f.get("encoding") == "base64":
        open(p,"wb").write(base64.b64decode(c))
    else:
        open(p,"w",encoding="utf-8",newline="\n").write(c)
print("Wrote", len(data), "files")
PY
          git status --porcelain

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: apply automated patch"
            git push
          fi
